name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Frida on GitHub Actions Host
        run: |
          pip install frida-tools
          wget https://github.com/frida/frida/releases/latest/download/frida-server-16.6.6-android-x86_64.xz
          mv frida-server-16.6.6-android-x86_64.xz frida-server.xz
          xz -d frida-server.xz
          chmod +x frida-server

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          script: |
            pwd 
            ls
            touch emulator.log                    # create log file
            chmod 777 emulator.log                # allow writing to log file
            adb logcat >> emulator.log &          # pipe all logcat messages into log file as a background process
            adb root
            adb push frida-server /data/local/tmp/
            adb shell "chmod 755 /data/local/tmp/frida-server"
            adb shell "nohup /data/local/tmp/frida-server > /dev/null 2>&1 &"
            frida-ps -Uai
            ./gradlew connectedCheck
            ls ./app/build/outputs/apk
            adb install ./app/build/outputs/apk/debug/app-debug.apk
            adb logcat >> temp.txt &
            frida-ps -Uai
            timeout 20s frida -U -f com.example.myapplication -l ./testingstuffdontgiveout/build.js > /dev/null 2>&1 &

      - name: whats in the log
        run: |
          cat temp.txt | grep "Emulator is"